#Trocar para o nome que ficara em /plugins
name: JobPlugin
#Trocar para a classe que extends JavaPlugin
main: com.github.argoninc.job.Principal
version: 1.0.0
api-version: 1.15
commands:
   setjob:
     description: Seta o job de alguem.
     usage: /<command>.